/** Light theme design tokens (`:root`). */
export const lightVariables = {
  /* surfaces */
  "--areia-background": "var(--color-white)",
  "--areia-foreground": "var(--color-neutral-900, oklch(21% 0.006 285.885))",
  "--areia-surface": "var(--color-neutral-50, oklch(98.5% 0 0))",
  "--areia-surface-foreground": "var(--color-neutral-900, oklch(21% 0.006 285.885))",
  "--areia-surface-muted": "var(--color-neutral-100, oklch(97% 0 0))",
  "--areia-surface-muted-foreground": "var(--color-neutral-500, oklch(55.6% 0 0))",
  "--areia-surface-elevated": "var(--color-white, #fff)",
  "--areia-surface-elevated-foreground": "var(--color-neutral-950, oklch(14.5% 0 0))",
  "--areia-overlay": "oklch(0% 0 0 / 0.4)",
  "--areia-border": "var(--color-neutral-200)",
  "--areia-input": "var(--color-white, #fff)",
  "--areia-ring": "var(--areia-primary)",
  "--areia-divider": "oklch(14.5% 0 0 / 0.1)",

  /* text */
  "--areia-text-default": "var(--color-neutral-900, oklch(21% 0.006 285.885))",
  "--areia-text-strong": "var(--color-neutral-950, oklch(14.5% 0 0))",
  "--areia-text-subtle": "var(--color-neutral-500, oklch(55.6% 0 0))",
  "--areia-text-muted": "var(--color-neutral-400, oklch(70.8% 0 0))",
  "--areia-text-placeholder": "var(--color-neutral-400, oklch(70.8% 0 0))",
  "--areia-text-inverse": "var(--color-neutral-100, oklch(97% 0 0))",
  "--areia-text-disabled": "var(--color-neutral-300, oklch(87% 0 0))",

  /* brand & accent */
  "--areia-primary": "oklch(0.5772 0.2324 260)",
  "--areia-primary-foreground": "var(--color-white, #fff)",
  "--areia-primary-soft": "color-mix(in oklch, var(--areia-primary) 14%, var(--areia-background))",
  "--areia-primary-soft-foreground": "var(--areia-primary)",
  "--areia-accent": "#f6821f",
  "--areia-accent-foreground": "var(--color-white, #fff)",
  "--areia-accent-soft": "var(--color-orange-100, oklch(95.4% 0.038 75.164))",
  "--areia-accent-soft-foreground": "var(--color-orange-800, oklch(47% 0.157 37.304))",
  "--areia-badge-neutral": "var(--color-neutral-600, oklch(43.9% 0 0))",
  "--areia-badge-neutral-foreground": "var(--color-white, #fff)",
  "--areia-badge-purple": "var(--color-purple-600, oklch(60% 0.118 184.704))",
  "--areia-badge-purple-foreground": "var(--color-white, #fff)",
  "--areia-badge-teal": "var(--color-teal-600, oklch(60% 0.118 184.704))",
  "--areia-badge-teal-foreground": "var(--color-white, #fff)",
  "--areia-badge-teal-soft": "var(--color-teal-100, oklch(95.3% 0.051 180.801))",
  "--areia-badge-teal-soft-foreground": "var(--color-teal-800, oklch(43.7% 0.078 188.216))",

  /* status */
  "--areia-success": "var(--color-green-600, oklch(62.7% 0.194 149.214))",
  "--areia-success-foreground": "var(--color-white, #fff)",
  "--areia-success-soft": "var(--color-emerald-100, oklch(95% 0.052 163.051))",
  "--areia-success-soft-foreground": "var(--color-emerald-800, oklch(43.2% 0.095 166.913))",
  "--areia-info": "var(--color-blue-600, oklch(54.6% 0.245 262.881))",
  "--areia-info-foreground": "var(--color-white, #fff)",
  "--areia-info-soft": "var(--color-blue-100, oklch(93.2% 0.032 255.585))",
  "--areia-info-soft-foreground": "var(--color-blue-800, oklch(42.4% 0.199 265.638))",
  "--areia-warning": "var(--color-yellow-300, oklch(90.5% 0.182 98.111))",
  "--areia-warning-foreground": "var(--color-yellow-900, oklch(42.1% 0.095 57.708))",
  "--areia-warning-soft": "var(--color-yellow-100, oklch(97.3% 0.071 103.193))",
  "--areia-warning-soft-foreground": "var(--color-yellow-800, oklch(47.6% 0.114 61.907))",
  "--areia-destructive": "var(--color-red-500, oklch(63.7% 0.237 25.331))",
  "--areia-destructive-foreground": "var(--color-white, #fff)",
  "--areia-destructive-soft": "var(--color-red-100, oklch(93.6% 0.032 17.717))",
  "--areia-destructive-soft-foreground": "var(--color-red-700, oklch(50.5% 0.213 27.518))",

  /* controls */
  "--areia-control-background": "var(--areia-surface)",
  "--areia-control-foreground": "var(--areia-text-default)",
  "--areia-control-border": "var(--areia-border)",
  "--areia-control-hover": "var(--areia-surface-muted)",
  "--areia-control-active": "var(--color-neutral-200, oklch(92.2% 0 0))",
  "--areia-control-disabled": "oklch(100% 0 0 / 0.5)",
  "--areia-control-disabled-foreground": "var(--areia-text-disabled)",

  /* typography */
  "--areia-font-sans": '"Geist Variable", system-ui, sans-serif',
  "--areia-font-mono": '"Geist Mono Variable", ui-monospace, SFMono-Regular, Menlo, monospace',
  "--areia-text-xs": "12px",
  "--areia-text-xs-line-height": "1.2",
  "--areia-text-sm": "13px",
  "--areia-text-sm-line-height": "1.35",
  "--areia-text-md": "14px",
  "--areia-text-md-line-height": "1.5",
  "--areia-text-lg": "16px",
  "--areia-text-lg-line-height": "1.5",
  "--areia-text-xl": "20px",
  "--areia-text-xl-line-height": "1.4",

  /* spacing */
  "--areia-space-0": "0px",
  "--areia-space-1": "4px",
  "--areia-space-2": "8px",
  "--areia-space-3": "12px",
  "--areia-space-4": "16px",
  "--areia-space-5": "20px",
  "--areia-space-6": "24px",

  /* radius */
  "--areia-radius-none": "0",
  "--areia-radius-sm": "0.25rem",
  "--areia-radius-md": "0.375rem",
  "--areia-radius-lg": "0.5rem",
  "--areia-radius-full": "999px",

  /* shadows */
  "--areia-shadow-none": "none",
  "--areia-shadow-sm": "0 1px 2px 0 oklch(0% 0 0 / 0.05)",
  "--areia-shadow-md": "0 4px 6px -1px oklch(0% 0 0 / 0.1), 0 2px 4px -2px oklch(0% 0 0 / 0.1)",
  "--areia-shadow-lg": "0 10px 15px -3px oklch(0% 0 0 / 0.1), 0 4px 6px -4px oklch(0% 0 0 / 0.1)",

  /* z-index */
  "--areia-z-base": "0",
  "--areia-z-sticky": "10",
  "--areia-z-dropdown": "20",
  "--areia-z-tooltip": "30",
  "--areia-z-modal": "40",
  "--areia-z-toast": "50",
} as const;

/** Dark theme overrides (`.dark`). */
export const darkVariables = {
  "--areia-background": "oklch(10% 0 0)",
  "--areia-foreground": "var(--color-neutral-100)",
  "--areia-surface": "var(--color-neutral-900)",
  "--areia-surface-foreground": "var(--color-neutral-100)",
  "--areia-surface-muted": "var(--color-neutral-800)",
  "--areia-surface-muted-foreground": "var(--color-neutral-400)",
  "--areia-surface-elevated": "var(--color-neutral-900)",
  "--areia-surface-elevated-foreground": "var(--color-neutral-50)",
  "--areia-overlay": "oklch(0% 0 0 / 0.65)",
  "--areia-border": "var(--color-neutral-800)",
  "--areia-input": "var(--color-neutral-900)",
  "--areia-ring": "var(--areia-primary)",
  "--areia-divider": "var(--color-neutral-800)",

  "--areia-text-default": "var(--color-neutral-100)",
  "--areia-text-strong": "var(--color-neutral-50)",
  "--areia-text-subtle": "var(--color-neutral-400)",
  "--areia-text-muted": "var(--color-neutral-500)",
  "--areia-text-placeholder": "var(--color-neutral-500)",
  "--areia-text-inverse": "var(--color-neutral-900)",
  "--areia-text-disabled": "var(--color-neutral-600)",

  "--areia-primary-soft": "color-mix(in oklch, var(--areia-primary) 32%, var(--areia-background))",
  "--areia-primary-soft-foreground": "var(--areia-primary)",
  "--areia-accent-soft": "var(--color-orange-900)",
  "--areia-accent-soft-foreground": "var(--color-orange-200)",
  "--areia-badge-purple": "var(--color-purple-700)",
  "--areia-badge-teal": "var(--color-teal-700)",
  "--areia-badge-teal-soft": "var(--color-teal-900)",
  "--areia-badge-teal-soft-foreground": "var(--color-teal-200)",

  "--areia-success": "var(--color-green-900)",
  "--areia-success-soft": "var(--color-emerald-900)",
  "--areia-success-soft-foreground": "var(--color-emerald-200)",
  "--areia-info": "var(--color-blue-900)",
  "--areia-info-soft": "var(--color-blue-900)",
  "--areia-info-soft-foreground": "var(--color-blue-400)",
  "--areia-warning": "var(--color-yellow-900)",
  "--areia-warning-soft": "var(--color-yellow-700)",
  "--areia-warning-soft-foreground": "var(--color-yellow-400)",
  "--areia-destructive": "var(--color-red-900)",
  "--areia-destructive-soft": "var(--color-red-900)",
  "--areia-destructive-soft-foreground": "var(--color-red-400)",

  "--areia-control-background": "var(--areia-surface)",
  "--areia-control-foreground": "var(--areia-text-default)",
  "--areia-control-border": "var(--areia-border)",
  "--areia-control-hover": "var(--areia-surface-muted)",
  "--areia-control-active": "var(--color-neutral-700)",
  "--areia-control-disabled": "oklch(17% 0 0 / 0.5)",
  "--areia-control-disabled-foreground": "var(--areia-text-disabled)",
} as const;

/** Tailwind `@theme` mappings for Areia utilities. */
export const themeVariables = {
  "--font-sans": "var(--areia-font-sans)",
  "--font-mono": "var(--areia-font-mono)",

  "--color-areia-background": "var(--areia-background)",
  "--color-areia-foreground": "var(--areia-foreground)",
  "--color-areia-surface": "var(--areia-surface)",
  "--color-areia-surface-foreground": "var(--areia-surface-foreground)",
  "--color-areia-surface-muted": "var(--areia-surface-muted)",
  "--color-areia-surface-muted-foreground": "var(--areia-surface-muted-foreground)",
  "--color-areia-surface-elevated": "var(--areia-surface-elevated)",
  "--color-areia-surface-elevated-foreground": "var(--areia-surface-elevated-foreground)",
  "--color-areia-overlay": "var(--areia-overlay)",
  "--color-areia-border": "var(--areia-border)",
  "--color-areia-input": "var(--areia-input)",
  "--color-areia-ring": "var(--areia-ring)",
  "--color-areia-divider": "var(--areia-divider)",
  "--color-areia-primary": "var(--areia-primary)",
  "--color-areia-primary-foreground": "var(--areia-primary-foreground)",
  "--color-areia-primary-soft": "var(--areia-primary-soft)",
  "--color-areia-primary-soft-foreground": "var(--areia-primary-soft-foreground)",
  "--color-areia-accent": "var(--areia-accent)",
  "--color-areia-accent-foreground": "var(--areia-accent-foreground)",
  "--color-areia-accent-soft": "var(--areia-accent-soft)",
  "--color-areia-accent-soft-foreground": "var(--areia-accent-soft-foreground)",
  "--color-areia-badge-neutral": "var(--areia-badge-neutral)",
  "--color-areia-badge-neutral-foreground": "var(--areia-badge-neutral-foreground)",
  "--color-areia-badge-purple": "var(--areia-badge-purple)",
  "--color-areia-badge-purple-foreground": "var(--areia-badge-purple-foreground)",
  "--color-areia-badge-teal": "var(--areia-badge-teal)",
  "--color-areia-badge-teal-foreground": "var(--areia-badge-teal-foreground)",
  "--color-areia-badge-teal-soft": "var(--areia-badge-teal-soft)",
  "--color-areia-badge-teal-soft-foreground": "var(--areia-badge-teal-soft-foreground)",
  "--color-areia-success": "var(--areia-success)",
  "--color-areia-success-foreground": "var(--areia-success-foreground)",
  "--color-areia-success-soft": "var(--areia-success-soft)",
  "--color-areia-success-soft-foreground": "var(--areia-success-soft-foreground)",
  "--color-areia-info": "var(--areia-info)",
  "--color-areia-info-foreground": "var(--areia-info-foreground)",
  "--color-areia-info-soft": "var(--areia-info-soft)",
  "--color-areia-info-soft-foreground": "var(--areia-info-soft-foreground)",
  "--color-areia-warning": "var(--areia-warning)",
  "--color-areia-warning-foreground": "var(--areia-warning-foreground)",
  "--color-areia-warning-soft": "var(--areia-warning-soft)",
  "--color-areia-warning-soft-foreground": "var(--areia-warning-soft-foreground)",
  "--color-areia-destructive": "var(--areia-destructive)",
  "--color-areia-destructive-foreground": "var(--areia-destructive-foreground)",
  "--color-areia-destructive-soft": "var(--areia-destructive-soft)",
  "--color-areia-destructive-soft-foreground": "var(--areia-destructive-soft-foreground)",
  "--color-areia-control-background": "var(--areia-control-background)",
  "--color-areia-control-foreground": "var(--areia-control-foreground)",
  "--color-areia-control-border": "var(--areia-control-border)",
  "--color-areia-control-hover": "var(--areia-control-hover)",
  "--color-areia-control-active": "var(--areia-control-active)",
  "--color-areia-control-disabled": "var(--areia-control-disabled)",
  "--color-areia-control-disabled-foreground": "var(--areia-control-disabled-foreground)",

  "--text-color-areia-default": "var(--areia-text-default)",
  "--text-color-areia-strong": "var(--areia-text-strong)",
  "--text-color-areia-subtle": "var(--areia-text-subtle)",
  "--text-color-areia-muted": "var(--areia-text-muted)",
  "--text-color-areia-placeholder": "var(--areia-text-placeholder)",
  "--text-color-areia-inverse": "var(--areia-text-inverse)",
  "--text-color-areia-disabled": "var(--areia-text-disabled)",

  "--text-xs": "var(--areia-text-xs)",
  "--text-xs--line-height": "var(--areia-text-xs-line-height)",
  "--text-sm": "var(--areia-text-sm)",
  "--text-sm--line-height": "var(--areia-text-sm-line-height)",
  "--text-base": "var(--areia-text-md)",
  "--text-base--line-height": "var(--areia-text-md-line-height)",
  "--text-lg": "var(--areia-text-lg)",
  "--text-lg--line-height": "var(--areia-text-lg-line-height)",
  "--text-xl": "var(--areia-text-xl)",
  "--text-xl--line-height": "var(--areia-text-xl-line-height)",
};
