import { defineMeta } from "blume";

export default defineMeta({
  pages: [
    "getting-started",
    "badge",
    "banner",
    "breadcrumbs",
    "button",
    "checkbox",
    "clipboard-text",
    "command-palette",
    "collapsible",
    "combobox",
    "context-menu",
    "date-picker",
    "dialog",
    "dropdown",
    "field",
    "form",
    "hover-card",
    "icon",
    "input",
    "label",
    "layer-card",
    "link",
    "pagination",
    "popover",
    "progress",
    "radio",
    "resizable",
    "select",
    "slider",
    "sonner",
    "spinner",
    "switch",
    "table",
    "tabs",
    "textarea",
    "toggle",
    "tooltip",
  ],
});
